### PR TITLE
Add pre-publish build step to fix installing insect from npm

### PR DESCRIPTION
**Pull request by n4bb12**
Fixes https://github.com/sharkdp/insect/issues/224

I renamed the `postinstall` script to `setup` to avoid it being run when used as a CLI tool or dependency.

The `setup` and `build` script are run in the `prepack` phase of the publish command, so you don't need to do anything. Just run `npm publish` as per usual.

For convenience the `setup` script is also run on `npm start`. It's fast, so it's ok to do that and it's convenient to not need to think about any of this when contributing.

I listed the files required for publishing in the `package.json` to avoid uploading unnecessary files. From testing it seems to only need the `output` folder to run. If I'm mistaken, please correct me. I also added the `insect.png` because it is used in the README. README, LICENSE and index.js are included by default.

As a small improvement I changed the copy script to copy files in parallel.

You can try this out:

```
# terminal 1
npx verdaccio
```

```
# terminal 2
export npm_config_registry=http://localhost:4873
npm version patch
npm publish
npx insect@5.4.1 '1 + 1'
```

If you want to just see what's being published and the above does not work, you can also do

```
npm pack
```

This will give you the archive that would be published and you can just open it and have a look inside.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for working on this!

For some reason, the build fails: https://travis-ci.org/github/sharkdp/insect/builds/730488027

I have to admit that it currently also fails on `master` (it used to work, and the tests still run fine locally) .... but with a different error message: https://travis-ci.org/github/sharkdp/insect/builds/730376983

**Comment by n4bb12** [comment]
I don't know why purescript is installed manually in the travis config. I think it shouldn't be because it's already installed through npm and that would also make it different from the local setup.

I also updated the build dependencies, maybe it fixes something.

**Comment by n4bb12** [comment]
Fixed ✨

**Review by sharkdp — APPROVED** [review]
Thank you so much!

**Pull request merged**
