### PR TITLE
Add local dev server

### LINKED ISSUE #179: Reloading insect.sh causes queries to pile up
How to reproduce?

* Go to https://insect.sh/
* type `1`, press `Enter`. The URL changes to https://insect.sh/?q=1 (as expected)
* Now hit refresh (`F5` or `Ctrl+Shift+R`). The URL changes to https://insect.sh/?q=1?q=1
* Hit refresh again. The URL changes to https://insect.sh/?q=1?q=1?q=1%3Fq%3D1 which causes a parse error.

@n4bb12 CC-ing you just in case you are interested in looking into this. If not, sorry for the ping.

### PR DESCRIPTION
**Pull request by n4bb12**
Resolves #179.

The first commit adds `live-server` for local development and a `server` script in `package.json` for starting it.

For some added convenience I used `npm-run-all` to start both the server and `pulp -w browserify` in parallel in the `start` script. So now both tasks are started with `npm start` with just one terminal.

The second commit is a revert of https://github.com/sharkdp/insect/commit/be35784a177bbdc2353e84b98dabea07d5612b60.

### CODE REVIEW

**Comment by sharkdp** [comment]
This is really great, thank you very much!

The live-server works for me, but I do need to call `build.sh` after `npm install`. I guess this is still needed?

**Comment by n4bb12** [comment]
This didn't work for you? https://github.com/sharkdp/insect/pull/180
Maybe I added the wrong build, I'll check

**Comment by sharkdp** [comment]
I guess the `build` command only runs `pulp build -m Insect`, as specified in the `package.json`, but we also need to run the bash script to copy the files(?).

**Comment by n4bb12** [comment]
You are right, we actually need to run `build.sh`.

The problem with that is that it assumes a bash.
What do you think of using something cross-platform? Perhaps [cpx](https://www.npmjs.com/package/cpx#example) from npm?

**Comment by sharkdp** [comment]
> Unfortunately it's not very cross-platform as it assumes a bash.
> What do you think replacing the `cp` part with [cpx](https://www.npmjs.com/package/cpx#example) from npm to ensure it works for everyone?

Sounds fantastic. We can leave the `nexe`-part in the `build.sh` script and implement the copying in JS.

**Comment by sharkdp** [comment]
Merging this, because it's not really related to the discussion. Thank you very much!

**Pull request merged**
