### PR TITLE
Implement insectrc (closes #107)

### LINKED ISSUE #107: Add configuration command
Some things came up that a user might want to configure:
- number of significant digits that are displayed (default: 6)
- ~decimal separator: `.` vs `,`~
- terminal prompt
- pretty printing: on/off
- ...

I'd like to introduce a new keyword (e.g. `set`) that can control these:
```
> set displayed_digits 10
> set prompt "insect >>> "
```

Then, in a second step, we could read in a file like `~/.config/insectrc` during startup where these settings (and user-defined variables) could be stored. For the web-version, settings could be stored in `localStorage`.

### PR DESCRIPTION
**Pull request by Mstrodl**
On startup, insect will read and execute `~/.insectrc` before evaluating anything. If this behaviour isn't desired, the user can simply set the `INSECT_NO_RC` environment variable to `true` to disable it.

This is useful for a few reasons. Personally, I'm using it to keep some commonly-used functions:
```
cosecant(x)=1/sin(x)
csc(x)=cosecant(x)

secant(x)=1/cos(x)

cotangent(x)=1/tan(x)
cot(x)=cotangent(x)
```

### CODE REVIEW

**Comment by sharkdp** [comment]
Awesome, thank you very much for your contribution!

**Comment by davidrihtarsic** [comment]
Hi,
can you help me with the implementation of `.insectrc`?
I'm using insect from AUR:
```
╰> pacman -Qi insect
Name            : insect
Version         : 5.6.0-2
...
```
I have created the `.insectrc` file in my home dir.:
```
╰> ls -al ~/.ins*
-rw-r--r-- 1 david users 48 Sep 30 10:10 /home/david/.insectrc
```
with the content:
```
╰> cat .insectrc
set displayed_digits 10
set prompt "insect >>>"
```
when I run insect nothing is changed
```
╰> insect
>>> pi
  pi
   = 3.14159
```
... so, what am I doing wrong?

**Comment by Mstrodl** [comment]
@davidrihtarsic your insectrc is not valid insect stuff:
image

**Comment by davidrihtarsic** [comment]
@Mstrodl thx for the answer. OK, fair enough... I changed the content in `.insectrc` to:
```
╰> cat .insectrc
multi(x,y)=x*y
```
... but when I run insect, the function not working:
```
╰> insect
>>> multi(2,3)
  Parse error at position 8: Expected ")"
>>>
```
However, if I run these commands inside insect, I get these results:
```
╰> insect
>>> multi(x,y)=x*y
  multi(x, y) = x × y
>>> multi(2,3)
  multi(2, 3)
   = 6
>>>
```
I really love insect, I use it on a daily basis, but it would be very nice to have some personal functions inside. Does anyone knows if there is a way to run it in debug mode e.g.:
```
insect --verbose
```
... do you have any other ideas?

**Comment by sharkdp** [comment]
How did you install insect? I guess I haven't released a new version since this feature was merged.

**Comment by davidrihtarsic** [comment]
@sharkdp thx for your comment.
As I wrote, I'm using `insect` from AUR (on Linux) and currently running version: `5.6.0-2`. OK, if this feature is not jet available I'll wait and I look forward to it.

**Comment by sharkdp** [comment]
This is now available in v5.7.0. I also updated the insect package on AUR. Let me know if this works, @davidrihtarsic

**Comment by gennaro-tedesco** [comment]
Very excited to have the `.insectrc`! Do we have some lines of documentation somewhere that indicate the grammar for it or does it simply accept any `insect` valid expression?

**Comment by sharkdp** [comment]
> Do we have some lines of documentation somewhere that indicate the grammar for it or does it simply accept any `insect` valid expression?

The latter, correct. There's nothing special about the insectrc environment.

**Comment by sharkdp** [comment]
Oh, right. I'll reopen that ticket.

> which makes the `.insectrc` at the moment only accepting user-defined functions

.. and variables, yes.

**Pull request merged**
