### PR TITLE
Change -> to ➞

### PR DESCRIPTION
**Pull request by perryprog**
In PrettyPrint I changed the -> to ➞, if you want another unicode arrow that's fine — this is the best one I found that works well in a terminal.

This also breaks the tests which after a good bit I could not get to pass, so if you could help me with that, that would be great.

Additionally, I don't know PureScript (though it looks really cool), so any help is appreciated.

### CODE REVIEW

**Comment by perryprog** [comment]
Also, I accidentally committed those tests. I'm trying to revert that now.

**Comment by sharkdp** [comment]
Thank you for your contribution!

What is the motivation behind this? Just to have a nicer pretty-printing output?

Concerning the failing tests:
The output of the pretty printer should always be valid syntax, i.e. the parser should be able to read it. This property is currently validated by the `prettyPrintCheck` tests. I guess that these tests currently fail because `➞` is not valid syntax (`→` is, though - but it doesn't look very nice with the default font on insect.sh).

**Comment by perryprog** [comment]
Yeah, it's a really small contribution that's basically just a big nit. I find it a lot easier to read because ➞ takes less effort than -> to realize it's an arrow (at least that's how I feel) 

I have the same kinda thing with ligatures, and it's the same reason I switched completely over the Fira Code for programming.

**Comment by light2yellow** [comment]
I'm not really into this, but don't forget about fonts with ligatures that will make their own variant of `->`. They might not want it to become `➞` for every font supporting ligatures.

**Comment by light2yellow** [comment]
(if only they explicitly define that `->` is directly substituted with their own variant of `➞`, which might not be true for all ligature-full fonts)

**Comment by perryprog** [comment]
True... it would be nice to have a config file where you could set all these details. For example: 
```
arrowChar: ➞
prompt: %D >>>
```
Anyway that would be a cool way to easily increase customization.

**Comment by sharkdp** [comment]
If we want to integrate this, we need to make `➞` valid syntax (in addition to the other aliases for the conversion operator). The tests would also have to be adapted as some of them rely on the pretty-printing output to be `->`.

**Comment by perryprog** [comment]
Unfortunately I don't think I know PureScript well enough to do this. Sorry!

**Comment by perryprog** [comment]
I assume you'll get tests to pass later?

**Comment by sharkdp** [comment]
... yes, almost done :smile: ...

**Comment by sharkdp** [comment]
I have to say I like this! Tests pass, changes are live.

**Comment by perryprog** [comment]
@sharkdp did you `npm publish`? I see it works on the website, but I don't see the CLI version to be working.

**Comment by sharkdp** [comment]
Just released [v4.7.0](https://github.com/sharkdp/insect/releases/tag/v4.7.0)

**Pull request merged**
