### PR TITLE
Implement 'copy' command

### LINKED ISSUE #240: clipboard integration
Apologies if this is already supported and I just haven't found the right documentation (I have looked).

I frequently open a calculator to do a quick sum, with the intention of inserting the result into another application - usually via the clipboard. Having to pick up a mouse to select stuff is obviously not optimal.

I can think of a couple of ways to do this:
- echo `ans` to STDOUT on exit (possibly using a different command so as not to change the behaviour of `exit`/`quit`). It appears that if an expression is provided on STDIN, this is already the behaviour.
- introduce a new command that has the effect of putting the current `ans` onto the user's clipboard.

Both the above have their uses, so I think having both would be ideal.

I have never looked at purescript before, but I'm happy attempt a PR if there's interest?

### PR DESCRIPTION
**Pull request by benmaddison**
fixes #240 

Provides `copy` command (and `cp` alias) to put the current value of `ans` in the users clipboard.
Tested in FF and natively on X.

Browser support uses built-in `navigator.clipboard`, so will probably only work on (very?) recent browsers.
This can be fixed if necessary at the expense of an external dependency.

The structure of `res.newEnv.values` doesn't appear to be usable in JS, so I have hi-jacked the `msg` field to provide the value to the UI instead. This feels a bit hacky, so alternative suggestions are welcome.
Also, I have no idea what ideomatic purescript should look like... ;-)

Lastly, I have included the changes made by `npm` to my local `package-lock.json` in a separate commit, so that is easy to revert if necessary?

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

This looks - and works - great.

Could you please adapt `docs/reference-syntax.md` and re-run `docs/generate.sh`?

> Browser support uses built-in `navigator.clipboard`, so will probably only work on (very?) recent browsers.

I'm okay with that.

> Lastly, I have included the changes made by `npm` to my local `package-lock.json`

:+1:

**Comment by sharkdp** [comment]
I already pushed a version from your branch to https://insect.sh/ :smile:

**Comment by benmaddison** [comment]
> Thank you very much for your contribution!
> 
> This looks - and works - great.
> 
Great. You're welcome. I'm glad the purescript bits didn't make your eyes bleed.

> Could you please adapt `docs/reference-syntax.md` and re-run `docs/generate.sh`?
> 
Done. You might want to add a shebang and `chmod +x` that script at some stage, btw.

**Comment by benmaddison** [comment]
@sharkdp would you cut a release with this when you have a sec?

**Comment by sharkdp** [comment]
Done: https://github.com/sharkdp/insect/releases

**Pull request merged**
