### PR TITLE
Fix web working from zip repositary

### PR DESCRIPTION
**Pull request by username1565**
Before this commit there was been an errors, here: https://username1565.github.io/insect/web/
Add to this folser JS-scripts from https://insect.sh/

https://insect.sh/jquery.mousewheel-min.js
https://insect.sh/jquery.terminal.min.js
https://insect.sh/jquery.min.js
https://insect.sh/keyboardevent-key-polyfill.js
https://insect.sh/insect.js

test: 
1. https://username1565.github.io/insect/web/
2. 5.4564 kW·h -> kcal
= 4694.8 kcal

SUCCESS!

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution. It's not entirely clear to me what this PR is supposed to achieve.

Insect is written in PureScript and some of the JavaScript files (which are needed for the web-version) are generated by the PureScript compiler from the sources in the `src/` folder. I don't want to track these auto-generated files in Git, they are build artifacts. Some of the other files are dependencies that can be installed via `npm` or `bower`. Please see the "Development" section of the README on how to set up your own version of Insect.

**Comment by username1565** [comment]
Your web-version not working from the folder "/web/index.html".

**Comment by sharkdp** [comment]
> Your web-version not working locally, from the folder "/web/index.html".

The web version is working fine if you follow the "Development" instructions in the README: https://github.com/sharkdp/insect#development

**Comment by username1565** [comment]
I just copy the JS scripts from https://insect.sh/ and put this in /web/ folder.
And this working for me locally.
As you can see here: https://username1565.github.io/insect/web/index.html?q=((%2B٣٬٤٥٦٫٧٨٩%20ГВт%20%2B%20(-᱘𑱔𞥙,𝍥𐋤%20мегаватт))%20×%20௨༥❼𐋠७𑇡២.೬௫᠗Ⅶ叄𐋩%20Hours)%20->%20ExaJoules
this working from "/web/index.html" from my branch:
https://github.com/username1565/insect/archive/master.zip

**Comment by sharkdp** [comment]
It works, but I don't want to include these changes for the reasons given above ("I don't want to track these auto-generated files in Git, they are build artifacts").

**Pull request closed without merging**
