### PR TITLE
Add ideal gas constant R

### LINKED ISSUE #158: Add the ideal gas constant?
I find myself using insect a lot in thermodynamics, and it would be nice if it had the ideal gas constant.

    R = 8.3145 J/mol K

### PR DESCRIPTION
**Pull request by anilanar**
Fixes #158

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

It would be great if we could define that constant in [purescript-quantities](https://github.com/sharkdp/purescript-quantities) and just import it into Insect.

**Comment by sharkdp** [comment]
@anilanar Would you like to open a PR in purescript-quantities? I'd be happy to merge it and release a new version that could then be integrated into Insect.

**Comment by anilanar** [comment]
Will do it soon.
On 5. Oct 2018, 08:59 +0200, David Peter <notifications@github.com>, wrote:

@anilanar<https://github.com/anilanar> Would you like to open a PR in purescript-quantities? I'd be happy to merge it and release a new version that could then be integrated into Insect.

**Comment by anilanar** [comment]
The PR is ready.

**Comment by sharkdp** [comment]
The updated version is online.

**Pull request merged**
