### PR TITLE
Adding "mil" and "mils" to Parser

### PR DESCRIPTION
**Pull request by tomioe**
As discussed in this issue: https://github.com/sharkdp/insect/pull/195

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution!

Could you please also update the documentation accordingly (see analogous changes in the `thou` pull request).

**Comment by tomioe** [comment]
Done deal! Sorry about the delay, I missed your comment.

**Comment by tomioe** [comment]
> 
> 
> Done deal! Sorry about the delay, I missed your comment.

Nope, I messed up the PR (pushed to my own master branch instead of the PR branch...).
Should be going through now.

**Review by sharkdp — APPROVED** [review]
Thank you!

**Pull request merged**
