### PR TITLE
New parsing for knots and nautical miles

### PR DESCRIPTION
**Pull request by amportugal**
As issue: sharkdp/insect#190

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for the PR.

We'll have to wait for your other PR to get merged, then I have to release a new version, then we can integrate this here in Insect

**Comment by sharkdp** [comment]
https://github.com/sharkdp/purescript-quantities/releases/tag/v8.2.0

**Comment by sharkdp** [comment]
@amportugal Do you want to finish this?

**Comment by amportugal** [comment]
@sharkdp Sorry to have taken so long, haven't been available lately.

Updated version of purescript-quantities.

**Comment by sharkdp** [comment]
Thank you!

**Pull request merged**
